/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;
  isAdmin?: boolean;
  avatar?: string;
  createdAt: string;
}

export interface Lead {
  id: string;
  name: string;
  email: string;
  phone: string;
  businessName: string;
  brandUrl?: string; // Target brand link
  auditResponse?: string; // Stored brand audit text generated by Gemini
  status: string; // 'pending' | 'processed' | 'contacted'
  createdAt: string;
}

export interface Message {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  createdAt: string;
}

export interface ServiceItem {
  id: string;
  title: string;
  tagline: string;
  description: string;
  benefits: string[];
  iconName: string; // lucide icon name
  priceStarting: string;
  image?: string;
}

export interface ProjectItem {
  id: string;
  title: string;
  category: string; // branding | logos | social-media | photography | videography | motion-graphics | websites
  description: string;
  image: string;
  beforeImage?: string;
  afterImage?: string;
  challenge: string;
  solution: string;
  results: string;
}

export interface TestimonialItem {
  id: string;
  name: string;
  business: string;
  rating: number;
  review: string;
  avatar: string;
}

export interface BlogPostItem {
  id: string;
  title: string;
  slug: string;
  category: string;
  summary: string;
  content: string;
  image: string;
  date: string;
  author: string;
  readTime: string;
}

export interface NewsletterSubscription {
  id: string;
  email: string;
  createdAt: string;
}
